spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/njucat?useUnicode=true&characterEncoing=utf-8
    username: root
    password: mysql057048

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    nju.se.zt.njucat: debug
  file:
    name: log/blog.log